[phases.setup]
nixPkgs = ["...", "python311", "nodejs-16_x", "yarn"]

[phases.install]
cmds = ["yarn install"]

[phases.build]
cmds = ["yarn build-ts && yarn generate-docs"]

[start]
cmd = "node dist/server.js"

[variables]
NODE_ENV = "production"