[phases.setup]
nixPkgs = ["...", "python311"]
aptPkgs = ["...", "openssh-client", "build-essential", "libssl3", "libssl-dev", "openssl", "python3-pip"]

[phases.install]
cmds = ["yarn install"]

[phases.build]
cmds = ["yarn build-ts"]

[start]
cmd = "node dist/server.js"

[variables]
NODE_ENV = "production"
