[phases.setup]
nixPkgs = ["...", "python311", "nodejs-16_x", "yarn"]
aptPkgs = ["...", "openssh-client", "build-essential", "libssl3", "libssl-dev", "openssl"]

[phases.install]
cmds = ["yarn install"]

[phases.build]
cmds = ["yarn build-ts && yarn generate-docs"]

[start]
cmd = "node dist/server.js"

[variables]
NODE_ENV = "production"